### ISSUE TITLE
Is the cocoapods still working ?

### ISSUE THREAD

**Issue by PhilippeRiegert** [NilStack/NKWatchActivityIndicator#4]
When I "pod install" I'm receiving this error message : 
    "[!] Unable to find a specification for `NKWatchActivityInidcator`"

And I can't find it on the cocoapods website :
    https://cocoapods.org/?q=NKWatchActivityInidcator

**Comment by NilStack** [comment]
Hi, @phyllipe :

sorry, there is a typo bug. Please try again with NKWatchActivityIndicator. So embarrassed.

**Comment by PhilippeRiegert** [comment]
Thanks !! Sorry I didn't noticed it ^^

**Comment by NilStack** [comment]
Hi, @phyllipe:
It's my fault to misuse in README. Thanks for opening this issue.
